apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: web-app
  labels:
    app: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app
      tier: web-app
  replicas: 3
  template:
    metadata:
      labels:
        app: demo-app
        tier: web-app
    spec:
      containers:
      - name: demo-app
        image: 552182293274.dkr.ecr.us-east-1.amazonaws.com/sample-web-app:1.0
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # Using `GET_HOSTS_FROM=dns` requires your cluster to
          # provide a dns service. As of Kubernetes 1.3, DNS is a built-in
          # service launched automatically. However, if the cluster you are using
          # does not have a built-in DNS service, you can instead
          # access an environment variable to find the master
          # service's host. To do so, comment out the 'value: dns' line above, and
          # uncomment
        ports:
        - containerPort: 8080
